name: refresh_cdn

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['build_release']
    types: [completed]

# 添加并发控制
concurrency:
  group: refresh-cdn
  cancel-in-progress: false

jobs:
  refresh:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 1

      - name: Install deps
        run: sudo apt-get install jq -y

      - name: Get Version
        id: local_version
        run: |
          version=$(cat dist/gkd.version.json5 | jq -r '.version')
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Check Remote Version
        id: version_check
        run: |
          max_retries=5
          attempt=0
          while [ $attempt -le $max_retries ]; do
            echo "Attempt $attempt of $max_retries"

            # 从 GitHub Raw 获取远程版本
            remote_version=$(curl -s https://raw.githubusercontent.com/${{ github.repository }}/main/dist/gkd.version.json5 | jq -r '.version')
            local_version=${{ steps.local_version.outputs.version }}

            echo "Remote version: $remote_version"
            echo "Local version: $local_version"

            if [ "$remote_version" -gt "$local_version" ]; then
              echo "Remote version ($remote_version) is newer than local version ($local_version)"
              echo "Skipping this workflow run to let the newer version handle it"
              echo "should_refresh=false" >> "$GITHUB_OUTPUT"
              exit 0
            fi

            if [ "$remote_version" = "$local_version" ]; then
              echo "Version match, proceeding to refresh CDN"
              echo "should_refresh=true" >> "$GITHUB_OUTPUT"
              break
            fi

            # 增加条件判断，最后一次尝试不等待
            if [ $attempt -lt $max_retries ]; then
              echo "Version mismatch, waiting $((60 + attempt * 30)) seconds..."
              sleep $((60 + attempt * 30))
            else
              echo "Final attempt failed, exiting..."
              echo "should_refresh=false" >> "$GITHUB_OUTPUT"
              exit 0
            fi

            attempt=$((attempt + 1))
          done

      - name: Refresh CDN
        if: steps.version_check.outputs.should_refresh == 'true'
        run: |
          curl -X GET https://purge.jsdelivr.net/gh/${{ github.repository }}@main/dist/gkd.json5
          curl -X GET https://purge.jsdelivr.net/gh/${{ github.repository }}@main/dist/gkd.version.json5